server:
  port: 8082

spring:
  application:
    name: tyt-mistake
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${TYT_DB_USER:postgres}
    password: ${TYT_DB_PASS:root123}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true

tyt:
  32Bit:
    feign-client:
      auth: http://localhost:8080