server:
  port: 8082

spring:
  application:
    name: tyt-mistake
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

tyt:
  32Bit:
    feign-client:
      auth: http://localhost:8080