server:
  port: 8081

spring:
  application:
    name: tyt-conduct
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: ${TYT_DB_USER:postgres}
    password: ${TYT_DB_PASS:root123}
  jpa:
    hibernate:
      ddl-auto: update

tyt:
  32Bit:
    feign-client:
      auth: http://host.docker.internal:8080