server:
  port: 8080

spring:
  application:
    name: tyt-auth
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: ${TYT_DB_USER:postgres}
    password: ${TYT_DB_PASS:root123}
  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: ${TYT_SECRET_KEY:maoCom}
      expiration: ${TYT_TOKEN_EXPIRATION:900000}   # default 15 minutes

tyt:
  32Bit:
    feign-client:
      conduct: http://host.docker.internal:8081

